FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 30

BIRD_WIDTH = FRAME_WIDTH
BIRD_HEIGHT = FRAME_HEIGHT + 200

CHESSBOARD_ROW_CORNERS = 6
CHESSBOARD_COL_CORNERS = 9

DEFAULT_BIRDSEYE_CONFIG_PATH = "../config/camera_perspective.npy"
EXTERNAL_BIRDSEYE_CONFIG_PATH = "../config/ext_camera_perspective.npy"
